spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/vekpod1
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8081
#  http://localhost:8080/realms/vekpod1/protocol/openid-connect/token

jwt:
  auth:
    converter:
      resource-id: vekpod1-rest-api
      principle-attribute: preferred_username